### ISSUE TITLE
renderToStaticMarkup

### ISSUE THREAD

**Issue by ramboza** [gabrielbull/react-router-server#9]
Hello,

Great project! Thanks! 

How can we render output with React.renderToStaticMarkup ?

**Comment by gabrielbull** [comment]
renderToStaticMarkup has not been implemented yet. It wouldn't be too long to implement it either because it could be a flag that gets pass to the renderPass function and decides wether to use renderToString or renderToStaticMarkup here: https://github.com/gabrielbull/react-router-server/blob/master/src/renderer/renderToString.js#L30

I'm a bit short on time this month to work on it but I'd gladly accept a PR. If you decide to make the changes, I think renderPass should be moved to its own file so that both renderToString and renderToStaticMarkup can use it.

**Comment by gabrielbull** [comment]
Added in newest release. Thanks for suggesting! 🎉
